from django.db import models

# Create your models here.
class UserLog(models.Model):
    # Automatically set this to now when the record is first created
    timestamp = models.TextField()
    
    # The actual log/message content from user
    user_input = models.TextField()

    # Response generated by the LLM
    model_response = models.TextField()

    # You can also add __str__ method to return a string representation of the object
    def __str__(self):
        return f"UserLog(timestamp={self.timestamp}, message={self.user_input}, response={self.model_response})"