# Generated by Django 3.2.25 on 2025-05-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='timestamp',
            field=models.TextField(),
        ),
    ]
