# Generated by Django 3.2.25 on 2025-05-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_userlog_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='message',
            new_name='user_input',
        ),
        migrations.AddField(
            model_name='userlog',
            name='model_response',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
