# Generated by Django 2.2 on 2025-05-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20250503_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
